error_message: Attempting to deserialize object on a CUDA device but torch.cuda.is_available()
  is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu')
  to map your storages to the CPU.
error_traceback: "  File \"/home/darlinne.soto/new_framework/ray-tune-search/execute_once_one_experiment.py\"\
  , line 16, in execute_once\n    result = h_search_unit(\n\n  File \"/home/darlinne.soto/new_framework/ray-tune-search/h_search_unit.py\"\
  , line 23, in h_search_unit\n    experiment_result = run_basic_experiment(\n\n \
  \ File \"/home/darlinne.soto/new_framework/ray-tune-search/basic/run_basic_experiment.py\"\
  , line 151, in run_basic_experiment\n    datasets = do_reduce(\n\n  File \"/home/darlinne.soto/new_framework/ray-tune-search/basic/do_reduce.py\"\
  , line 121, in do_reduce\n    reducer.fit(**fit_dsets)\n\n  File \"/home/darlinne.soto/.local/lib/python3.10/site-packages/librep/transforms/topo_ae.py\"\
  , line 134, in fit\n    model_state_dict = pickle.load(file_handler)\n\n  File \"\
  /home/darlinne.soto/.local/lib/python3.10/site-packages/torch/storage.py\", line\
  \ 241, in _load_from_bytes\n    return torch.load(io.BytesIO(b))\n\n  File \"/home/darlinne.soto/.local/lib/python3.10/site-packages/torch/serialization.py\"\
  , line 815, in load\n    return _legacy_load(opened_file, map_location, pickle_module,\
  \ **pickle_load_args)\n\n  File \"/home/darlinne.soto/.local/lib/python3.10/site-packages/torch/serialization.py\"\
  , line 1043, in _legacy_load\n    result = unpickler.load()\n\n  File \"/home/darlinne.soto/.local/lib/python3.10/site-packages/torch/serialization.py\"\
  , line 980, in persistent_load\n    wrap_storage=restore_location(obj, location),\n\
  \n  File \"/home/darlinne.soto/.local/lib/python3.10/site-packages/torch/serialization.py\"\
  , line 217, in default_restore_location\n    result = fn(storage, location)\n\n\
  \  File \"/home/darlinne.soto/.local/lib/python3.10/site-packages/torch/serialization.py\"\
  , line 182, in _cuda_deserialize\n    device = validate_cuda_device(location)\n\n\
  \  File \"/home/darlinne.soto/.local/lib/python3.10/site-packages/torch/serialization.py\"\
  , line 166, in validate_cuda_device\n    raise RuntimeError('Attempting to deserialize\
  \ object on a CUDA '\n"
error_type: <class 'RuntimeError'>
num_params: -1.0
num_trainable_params: -1.0
score: -0.1
