trial_id,config,error_type,error_message,error_traceback
a2cdacb8,"{'umap_ncomp': 4, 'umap_spread': 1.0291436034882608, 'umap_mdist': 1.328420191503884, 'umap_neigh': 64, 'umap_epochs': 202}",<class 'ValueError'>,cannot assign slice from input of different size,"  File ""/home/darlinne.soto/new_framework/ray-tune-search/hyperparameters_search.py"", line 136, in my_objective_function
    result = h_search_unit(

  File ""/home/darlinne.soto/new_framework/ray-tune-search/h_search_unit.py"", line 23, in h_search_unit
    experiment_result = run_basic_experiment(

  File ""/home/darlinne.soto/new_framework/ray-tune-search/basic/run_basic_experiment.py"", line 151, in run_basic_experiment
    datasets = do_reduce(

  File ""/home/darlinne.soto/new_framework/ray-tune-search/basic/do_reduce.py"", line 121, in do_reduce
    reducer.fit(**fit_dsets)

  File ""/usr/local/lib/python3.10/site-packages/umap/umap_.py"", line 2608, in fit
    ) = nearest_neighbors(

  File ""/usr/local/lib/python3.10/site-packages/umap/umap_.py"", line 329, in nearest_neighbors
    knn_search_index = NNDescent(

  File ""/usr/local/lib/python3.10/site-packages/pynndescent/pynndescent_.py"", line 804, in __init__
    leaf_array = rptree_leaf_array(self._rp_forest)

  File ""/usr/local/lib/python3.10/site-packages/pynndescent/rp_trees.py"", line 1097, in rptree_leaf_array
    return np.vstack(rptree_leaf_array_parallel(rp_forest))

  File ""/usr/local/lib/python3.10/site-packages/pynndescent/rp_trees.py"", line 1089, in rptree_leaf_array_parallel
    result = joblib.Parallel(n_jobs=-1, require=""sharedmem"")(

  File ""/usr/local/lib/python3.10/site-packages/joblib/parallel.py"", line 1952, in __call__
    return output if self.return_generator else list(output)

  File ""/usr/local/lib/python3.10/site-packages/joblib/parallel.py"", line 1595, in _get_outputs
    yield from self._retrieve()

  File ""/usr/local/lib/python3.10/site-packages/joblib/parallel.py"", line 1699, in _retrieve
    self._raise_error_fast()

  File ""/usr/local/lib/python3.10/site-packages/joblib/parallel.py"", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)

  File ""/usr/local/lib/python3.10/site-packages/joblib/parallel.py"", line 736, in get_result
    return self._return_or_raise()

  File ""/usr/local/lib/python3.10/site-packages/joblib/parallel.py"", line 754, in _return_or_raise
    raise self._result
"
