error_message: "Error(s) in loading state_dict for TopologicallyRegularizedAutoencoder:\n\
  \tMissing key(s) in state_dict: \"latent_norm\", \"autoencoder.encoder.0.weight\"\
  , \"autoencoder.encoder.0.bias\", \"autoencoder.encoder.2.weight\", \"autoencoder.encoder.2.bias\"\
  , \"autoencoder.encoder.4.weight\", \"autoencoder.encoder.4.bias\", \"autoencoder.decoder.0.weight\"\
  , \"autoencoder.decoder.0.bias\", \"autoencoder.decoder.2.weight\", \"autoencoder.decoder.2.bias\"\
  , \"autoencoder.decoder.4.weight\", \"autoencoder.decoder.4.bias\". \n\tUnexpected\
  \ key(s) in state_dict: \"epoch\", \"train_recon_error\", \"train_topo_error\",\
  \ \"train_error\", \"val_recon_error\", \"val_topo_error\", \"val_error\". "
error_traceback: "  File \"/home/darlinne.soto/new_framework/ray-tune-search/execute_once_one_experiment.py\"\
  , line 16, in execute_once\n    result = h_search_unit(\n\n  File \"/home/darlinne.soto/new_framework/ray-tune-search/h_search_unit.py\"\
  , line 23, in h_search_unit\n    experiment_result = run_basic_experiment(\n\n \
  \ File \"/home/darlinne.soto/new_framework/ray-tune-search/basic/run_basic_experiment.py\"\
  , line 151, in run_basic_experiment\n    datasets = do_reduce(\n\n  File \"/home/darlinne.soto/new_framework/ray-tune-search/basic/do_reduce.py\"\
  , line 121, in do_reduce\n    reducer.fit(**fit_dsets)\n\n  File \"/home/darlinne.soto/.local/lib/python3.10/site-packages/librep/transforms/topo_ae.py\"\
  , line 136, in fit\n    self.model.load_state_dict(model_state_dict)\n\n  File \"\
  /home/darlinne.soto/.local/lib/python3.10/site-packages/torch/nn/modules/module.py\"\
  , line 2041, in load_state_dict\n    raise RuntimeError('Error(s) in loading state_dict\
  \ for {}:\\n\\t{}'.format(\n"
error_type: <class 'RuntimeError'>
num_params: -1.0
num_trainable_params: -1.0
score: -0.1
